/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.07.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { ErrorObject, ErrorObjectFromJSON, ErrorObjectToJSON } from "../models";

/**
 *
 */
export class TraceApi extends runtime.BaseAPI {
  /**
   * Trace a dummy task through the entire system for logging purposes
   */
  async traceRaw(
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        this.configuration.apiKey("Authorization"); // RequestAuthorizer authentication
    }

    const response = await this.request(
      {
        path: `/trace`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Trace a dummy task through the entire system for logging purposes
   */
  async trace(
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<void> {
    await this.traceRaw(initOverrides);
  }
}
