/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.05.02
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DocCreationCertificate,
    DocCreationCertificateFromJSON,
    DocCreationCertificateFromJSONTyped,
    DocCreationCertificateToJSON,
} from './DocCreationCertificate';

/**
 * 
 * @export
 * @interface AttachTwinDocumentResponse
 */
export interface AttachTwinDocumentResponse {
    /**
     * 
     * @type {DocCreationCertificate}
     * @memberof AttachTwinDocumentResponse
     */
    creationCertificate?: DocCreationCertificate;
}

export function AttachTwinDocumentResponseFromJSON(json: any): AttachTwinDocumentResponse {
    return AttachTwinDocumentResponseFromJSONTyped(json, false);
}

export function AttachTwinDocumentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachTwinDocumentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'creationCertificate': !exists(json, 'creation_certificate') ? undefined : DocCreationCertificateFromJSON(json['creation_certificate']),
    };
}

export function AttachTwinDocumentResponseToJSON(value?: AttachTwinDocumentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'creation_certificate': DocCreationCertificateToJSON(value.creationCertificate),
    };
}

