/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateStickersBodyStickersValue } from './CreateStickersBodyStickersValue';
import {
    CreateStickersBodyStickersValueFromJSON,
    CreateStickersBodyStickersValueFromJSONTyped,
    CreateStickersBodyStickersValueToJSON,
} from './CreateStickersBodyStickersValue';

/**
 * 
 * @export
 * @interface CreateStickersBody
 */
export interface CreateStickersBody {
    /**
     * 
     * @type {{ [key: string]: CreateStickersBodyStickersValue; }}
     * @memberof CreateStickersBody
     */
    stickers?: { [key: string]: CreateStickersBodyStickersValue; };
}

/**
 * Check if a given object implements the CreateStickersBody interface.
 */
export function instanceOfCreateStickersBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateStickersBodyFromJSON(json: any): CreateStickersBody {
    return CreateStickersBodyFromJSONTyped(json, false);
}

export function CreateStickersBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStickersBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stickers': !exists(json, 'stickers') ? undefined : (mapValues(json['stickers'], CreateStickersBodyStickersValueFromJSON)),
    };
}

export function CreateStickersBodyToJSON(value?: CreateStickersBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stickers': value.stickers === undefined ? undefined : (mapValues(value.stickers, CreateStickersBodyStickersValueToJSON)),
    };
}

