/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateTimeseriesTablesResponseTimeseriesValue } from './CreateTimeseriesTablesResponseTimeseriesValue';
import {
    CreateTimeseriesTablesResponseTimeseriesValueFromJSON,
    CreateTimeseriesTablesResponseTimeseriesValueFromJSONTyped,
    CreateTimeseriesTablesResponseTimeseriesValueToJSON,
} from './CreateTimeseriesTablesResponseTimeseriesValue';

/**
 * 
 * @export
 * @interface CreateTimeseriesTable200Response
 */
export interface CreateTimeseriesTable200Response {
    /**
     * 
     * @type {{ [key: string]: CreateTimeseriesTablesResponseTimeseriesValue; }}
     * @memberof CreateTimeseriesTable200Response
     */
    timeseries?: { [key: string]: CreateTimeseriesTablesResponseTimeseriesValue; };
}

/**
 * Check if a given object implements the CreateTimeseriesTable200Response interface.
 */
export function instanceOfCreateTimeseriesTable200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateTimeseriesTable200ResponseFromJSON(json: any): CreateTimeseriesTable200Response {
    return CreateTimeseriesTable200ResponseFromJSONTyped(json, false);
}

export function CreateTimeseriesTable200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTimeseriesTable200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeseries': !exists(json, 'timeseries') ? undefined : (mapValues(json['timeseries'], CreateTimeseriesTablesResponseTimeseriesValueFromJSON)),
    };
}

export function CreateTimeseriesTable200ResponseToJSON(value?: CreateTimeseriesTable200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeseries': value.timeseries === undefined ? undefined : (mapValues(value.timeseries, CreateTimeseriesTablesResponseTimeseriesValueToJSON)),
    };
}

