/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.07.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateStickersResponseStickersValueAnyOf
 */
export interface CreateStickersResponseStickersValueAnyOf {
  /**
   *
   * @type {string}
   * @memberof CreateStickersResponseStickersValueAnyOf
   */
  error?: string;
}

export function CreateStickersResponseStickersValueAnyOfFromJSON(
  json: any
): CreateStickersResponseStickersValueAnyOf {
  return CreateStickersResponseStickersValueAnyOfFromJSONTyped(json, false);
}

export function CreateStickersResponseStickersValueAnyOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateStickersResponseStickersValueAnyOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    error: !exists(json, "error") ? undefined : json["error"],
  };
}

export function CreateStickersResponseStickersValueAnyOfToJSON(
  value?: CreateStickersResponseStickersValueAnyOf | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    error: value.error,
  };
}
