/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.05.02
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateTimeseriesTablesResponse,
    CreateTimeseriesTablesResponseFromJSON,
    CreateTimeseriesTablesResponseFromJSONTyped,
    CreateTimeseriesTablesResponseToJSON,
} from './CreateTimeseriesTablesResponse';
import {
    CreateTimeseriesTablesResponseTimeseriesValue,
    CreateTimeseriesTablesResponseTimeseriesValueFromJSON,
    CreateTimeseriesTablesResponseTimeseriesValueFromJSONTyped,
    CreateTimeseriesTablesResponseTimeseriesValueToJSON,
} from './CreateTimeseriesTablesResponseTimeseriesValue';

/**
 * 
 * @export
 * @interface CreateTimeseriesTable200Response
 */
export interface CreateTimeseriesTable200Response {
    /**
     * 
     * @type {{ [key: string]: CreateTimeseriesTablesResponseTimeseriesValue; }}
     * @memberof CreateTimeseriesTable200Response
     */
    timeseries?: { [key: string]: CreateTimeseriesTablesResponseTimeseriesValue; };
}

export function CreateTimeseriesTable200ResponseFromJSON(json: any): CreateTimeseriesTable200Response {
    return CreateTimeseriesTable200ResponseFromJSONTyped(json, false);
}

export function CreateTimeseriesTable200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTimeseriesTable200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeseries': !exists(json, 'timeseries') ? undefined : (mapValues(json['timeseries'], CreateTimeseriesTablesResponseTimeseriesValueFromJSON)),
    };
}

export function CreateTimeseriesTable200ResponseToJSON(value?: CreateTimeseriesTable200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeseries': value.timeseries === undefined ? undefined : (mapValues(value.timeseries, CreateTimeseriesTablesResponseTimeseriesValueToJSON)),
    };
}

