/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TimeseriesTablesResponse,
    TimeseriesTablesResponseFromJSON,
    TimeseriesTablesResponseFromJSONTyped,
    TimeseriesTablesResponseToJSON,
} from './TimeseriesTablesResponse';
import {
    TimeseriesTablesResponseTimeseriesValue,
    TimeseriesTablesResponseTimeseriesValueFromJSON,
    TimeseriesTablesResponseTimeseriesValueFromJSONTyped,
    TimeseriesTablesResponseTimeseriesValueToJSON,
} from './TimeseriesTablesResponseTimeseriesValue';

/**
 * 
 * @export
 * @interface CreateTimeseriesTable200Response
 */
export interface CreateTimeseriesTable200Response {
    /**
     * 
     * @type {{ [key: string]: TimeseriesTablesResponseTimeseriesValue; }}
     * @memberof CreateTimeseriesTable200Response
     */
    timeseries?: { [key: string]: TimeseriesTablesResponseTimeseriesValue; };
}

export function CreateTimeseriesTable200ResponseFromJSON(json: any): CreateTimeseriesTable200Response {
    return CreateTimeseriesTable200ResponseFromJSONTyped(json, false);
}

export function CreateTimeseriesTable200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTimeseriesTable200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeseries': !exists(json, 'timeseries') ? undefined : (mapValues(json['timeseries'], TimeseriesTablesResponseTimeseriesValueFromJSON)),
    };
}

export function CreateTimeseriesTable200ResponseToJSON(value?: CreateTimeseriesTable200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeseries': value.timeseries === undefined ? undefined : (mapValues(value.timeseries, TimeseriesTablesResponseTimeseriesValueToJSON)),
    };
}

