/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStickersBodyStickersValue
 */
export interface CreateStickersBodyStickersValue {
    /**
     * 
     * @type {string}
     * @memberof CreateStickersBodyStickersValue
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateStickersBodyStickersValue
     */
    recipients?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateStickersBodyStickersValue
     */
    validityTs?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateStickersBodyStickersValue
     */
    publish?: Array<CreateStickersBodyStickersValuePublishEnum>;
}


/**
 * @export
 */
export const CreateStickersBodyStickersValuePublishEnum = {
    Put: 'on_put',
    Remove: 'on_remove',
    Expire: 'on_expire'
} as const;
export type CreateStickersBodyStickersValuePublishEnum = typeof CreateStickersBodyStickersValuePublishEnum[keyof typeof CreateStickersBodyStickersValuePublishEnum];


/**
 * Check if a given object implements the CreateStickersBodyStickersValue interface.
 */
export function instanceOfCreateStickersBodyStickersValue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateStickersBodyStickersValueFromJSON(json: any): CreateStickersBodyStickersValue {
    return CreateStickersBodyStickersValueFromJSONTyped(json, false);
}

export function CreateStickersBodyStickersValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStickersBodyStickersValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'recipients': !exists(json, 'recipients') ? undefined : json['recipients'],
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
        'publish': !exists(json, 'publish') ? undefined : json['publish'],
    };
}

export function CreateStickersBodyStickersValueToJSON(value?: CreateStickersBodyStickersValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'recipients': value.recipients,
        'validity_ts': value.validityTs,
        'publish': value.publish,
    };
}

