/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IndexTable,
    IndexTableFromJSON,
    IndexTableFromJSONTyped,
    IndexTableToJSON,
} from './IndexTable';
import {
    TableError,
    TableErrorFromJSON,
    TableErrorFromJSONTyped,
    TableErrorToJSON,
} from './TableError';

/**
 * @type CreateIndexTablesResponseIndexesValue
 * 
 * @export
 */
export type CreateIndexTablesResponseIndexesValue = IndexTable | TableError;

export function CreateIndexTablesResponseIndexesValueFromJSON(json: any): CreateIndexTablesResponseIndexesValue {
    return CreateIndexTablesResponseIndexesValueFromJSONTyped(json, false);
}

export function CreateIndexTablesResponseIndexesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIndexTablesResponseIndexesValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...IndexTableFromJSONTyped(json, true), ...TableErrorFromJSONTyped(json, true) };
}

export function CreateIndexTablesResponseIndexesValueToJSON(value?: CreateIndexTablesResponseIndexesValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    if ("error" in value) {
        return { ...TableErrorToJSON(value)}
    }
    return { ...IndexTableToJSON(value) };
}

