/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserSecretPINResponse
 */
export interface CreateUserSecretPINResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateUserSecretPINResponse
     */
    pin?: string;
}

/**
 * Check if a given object implements the CreateUserSecretPINResponse interface.
 */
export function instanceOfCreateUserSecretPINResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateUserSecretPINResponseFromJSON(json: any): CreateUserSecretPINResponse {
    return CreateUserSecretPINResponseFromJSONTyped(json, false);
}

export function CreateUserSecretPINResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserSecretPINResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pin': !exists(json, 'pin') ? undefined : json['pin'],
    };
}

export function CreateUserSecretPINResponseToJSON(value?: CreateUserSecretPINResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pin': value.pin,
    };
}

