/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.07.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateStickersBodyStickersValue
 */
export interface CreateStickersBodyStickersValue {
  /**
   *
   * @type {string}
   * @memberof CreateStickersBodyStickersValue
   */
  message?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateStickersBodyStickersValue
   */
  recipients?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof CreateStickersBodyStickersValue
   */
  validityTs?: number;
}

export function CreateStickersBodyStickersValueFromJSON(
  json: any
): CreateStickersBodyStickersValue {
  return CreateStickersBodyStickersValueFromJSONTyped(json, false);
}

export function CreateStickersBodyStickersValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateStickersBodyStickersValue {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, "message") ? undefined : json["message"],
    recipients: !exists(json, "recipients") ? undefined : json["recipients"],
    validityTs: !exists(json, "validity_ts") ? undefined : json["validity_ts"],
  };
}

export function CreateStickersBodyStickersValueToJSON(
  value?: CreateStickersBodyStickersValue | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    recipients: value.recipients,
    validity_ts: value.validityTs,
  };
}
