/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.05.02
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserSecret
 */
export interface CreateUserSecret {
    /**
     * 
     * @type {string}
     * @memberof CreateUserSecret
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserSecret
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserSecret
     */
    secret?: string;
    /**
     * UTC timestamp denoting validity of the User Secret
     * @type {number}
     * @memberof CreateUserSecret
     */
    validityTs?: number;
    /**
     * UTC timestamp denoting when the User Secret was created
     * @type {number}
     * @memberof CreateUserSecret
     */
    createdTs?: number;
    /**
     * UTC timestamp denoting when the User Secret was last updated
     * @type {number}
     * @memberof CreateUserSecret
     */
    updatedTs?: number;
}

export function CreateUserSecretFromJSON(json: any): CreateUserSecret {
    return CreateUserSecretFromJSONTyped(json, false);
}

export function CreateUserSecretFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserSecret {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account': !exists(json, 'account') ? undefined : json['account'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'secret': !exists(json, 'secret') ? undefined : json['secret'],
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
        'createdTs': !exists(json, 'created_ts') ? undefined : json['created_ts'],
        'updatedTs': !exists(json, 'updated_ts') ? undefined : json['updated_ts'],
    };
}

export function CreateUserSecretToJSON(value?: CreateUserSecret | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account': value.account,
        'user': value.user,
        'secret': value.secret,
        'validity_ts': value.validityTs,
        'created_ts': value.createdTs,
        'updated_ts': value.updatedTs,
    };
}

