/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeletedSticker
 */
export interface DeletedSticker {
    /**
     * 
     * @type {string}
     * @memberof DeletedSticker
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof DeletedSticker
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof DeletedSticker
     */
    validityTs?: number;
    /**
     * 
     * @type {number}
     * @memberof DeletedSticker
     */
    createdTs?: number;
}

/**
 * Check if a given object implements the DeletedSticker interface.
 */
export function instanceOfDeletedSticker(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeletedStickerFromJSON(json: any): DeletedSticker {
    return DeletedStickerFromJSONTyped(json, false);
}

export function DeletedStickerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletedSticker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account': !exists(json, 'account') ? undefined : json['account'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
        'createdTs': !exists(json, 'created_ts') ? undefined : json['created_ts'],
    };
}

export function DeletedStickerToJSON(value?: DeletedSticker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account': value.account,
        'message': value.message,
        'validity_ts': value.validityTs,
        'created_ts': value.createdTs,
    };
}

