/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IndexColumns } from './IndexColumns';
import {
    IndexColumnsFromJSON,
    IndexColumnsFromJSONTyped,
    IndexColumnsToJSON,
} from './IndexColumns';
import type { IndexTableResponseStats } from './IndexTableResponseStats';
import {
    IndexTableResponseStatsFromJSON,
    IndexTableResponseStatsFromJSONTyped,
    IndexTableResponseStatsToJSON,
} from './IndexTableResponseStats';
import type { IndexTemplates } from './IndexTemplates';
import {
    IndexTemplatesFromJSON,
    IndexTemplatesFromJSONTyped,
    IndexTemplatesToJSON,
} from './IndexTemplates';

/**
 * 
 * @export
 * @interface DeleteIndexesTable200Response
 */
export interface DeleteIndexesTable200Response {
    /**
     * 
     * @type {IndexTableResponseStats}
     * @memberof DeleteIndexesTable200Response
     */
    stats: IndexTableResponseStats;
    /**
     * Rule
     * @type {string}
     * @memberof DeleteIndexesTable200Response
     */
    rule: string;
    /**
     * 
     * @type {IndexColumns}
     * @memberof DeleteIndexesTable200Response
     */
    properties: IndexColumns;
    /**
     * 
     * @type {IndexTemplates}
     * @memberof DeleteIndexesTable200Response
     */
    templates: IndexTemplates;
}

/**
 * Check if a given object implements the DeleteIndexesTable200Response interface.
 */
export function instanceOfDeleteIndexesTable200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stats" in value;
    isInstance = isInstance && "rule" in value;
    isInstance = isInstance && "properties" in value;
    isInstance = isInstance && "templates" in value;

    return isInstance;
}

export function DeleteIndexesTable200ResponseFromJSON(json: any): DeleteIndexesTable200Response {
    return DeleteIndexesTable200ResponseFromJSONTyped(json, false);
}

export function DeleteIndexesTable200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteIndexesTable200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': IndexTableResponseStatsFromJSON(json['stats']),
        'rule': json['rule'],
        'properties': IndexColumnsFromJSON(json['properties']),
        'templates': IndexTemplatesFromJSON(json['templates']),
    };
}

export function DeleteIndexesTable200ResponseToJSON(value?: DeleteIndexesTable200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': IndexTableResponseStatsToJSON(value.stats),
        'rule': value.rule,
        'properties': IndexColumnsToJSON(value.properties),
        'templates': IndexTemplatesToJSON(value.templates),
    };
}

