/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDocDownload
 */
export interface GetDocDownload {
    /**
     * path to Doc to download
     * @type {string}
     * @memberof GetDocDownload
     */
    url?: string;
    /**
     * UTC timestamp denoting validity of the provided download URL
     * @type {number}
     * @memberof GetDocDownload
     */
    validityTs?: number;
}

export function GetDocDownloadFromJSON(json: any): GetDocDownload {
    return GetDocDownloadFromJSONTyped(json, false);
}

export function GetDocDownloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDocDownload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
    };
}

export function GetDocDownloadToJSON(value?: GetDocDownload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'validity_ts': value.validityTs,
    };
}

