/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetTimeseriesTablesResponseStats } from './GetTimeseriesTablesResponseStats';
import {
    GetTimeseriesTablesResponseStatsFromJSON,
    GetTimeseriesTablesResponseStatsFromJSONTyped,
    GetTimeseriesTablesResponseStatsToJSON,
} from './GetTimeseriesTablesResponseStats';
import type { ServicesDatabaseUserAccessCommand } from './ServicesDatabaseUserAccessCommand';
import {
    ServicesDatabaseUserAccessCommandFromJSON,
    ServicesDatabaseUserAccessCommandFromJSONTyped,
    ServicesDatabaseUserAccessCommandToJSON,
} from './ServicesDatabaseUserAccessCommand';

/**
 * 
 * @export
 * @interface GetIndexTablesResponse
 */
export interface GetIndexTablesResponse {
    /**
     * 
     * @type {GetTimeseriesTablesResponseStats}
     * @memberof GetIndexTablesResponse
     */
    stats: GetTimeseriesTablesResponseStats;
    /**
     * Users and their Indexes Database access type
     * @type {{ [key: string]: ServicesDatabaseUserAccessCommand; }}
     * @memberof GetIndexTablesResponse
     */
    users?: { [key: string]: ServicesDatabaseUserAccessCommand; };
    /**
     * Index tables
     * @type {Array<string>}
     * @memberof GetIndexTablesResponse
     */
    indexes?: Array<string>;
}

/**
 * Check if a given object implements the GetIndexTablesResponse interface.
 */
export function instanceOfGetIndexTablesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stats" in value;

    return isInstance;
}

export function GetIndexTablesResponseFromJSON(json: any): GetIndexTablesResponse {
    return GetIndexTablesResponseFromJSONTyped(json, false);
}

export function GetIndexTablesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIndexTablesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': GetTimeseriesTablesResponseStatsFromJSON(json['stats']),
        'users': !exists(json, 'users') ? undefined : (mapValues(json['users'], ServicesDatabaseUserAccessCommandFromJSON)),
        'indexes': !exists(json, 'indexes') ? undefined : json['indexes'],
    };
}

export function GetIndexTablesResponseToJSON(value?: GetIndexTablesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': GetTimeseriesTablesResponseStatsToJSON(value.stats),
        'users': value.users === undefined ? undefined : (mapValues(value.users, ServicesDatabaseUserAccessCommandToJSON)),
        'indexes': value.indexes,
    };
}

