/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPin
 */
export interface GetPin {
    /**
     * User Secret PIN
     * @type {string}
     * @memberof GetPin
     */
    userPin?: string;
    /**
     * UTC timestamp denoting validity of the User Secret PIN
     * @type {number}
     * @memberof GetPin
     */
    validityTs?: number;
}

export function GetPinFromJSON(json: any): GetPin {
    return GetPinFromJSONTyped(json, false);
}

export function GetPinFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userPin': !exists(json, 'user_pin') ? undefined : json['user_pin'],
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
    };
}

export function GetPinToJSON(value?: GetPin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_pin': value.userPin,
        'validity_ts': value.validityTs,
    };
}

