/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LedgerAlias } from './LedgerAlias';
import {
    LedgerAliasFromJSON,
    LedgerAliasFromJSONTyped,
    LedgerAliasToJSON,
} from './LedgerAlias';

/**
 * 
 * @export
 * @interface GetTwinLedgerEntryLedgerParameter
 */
export interface GetTwinLedgerEntryLedgerParameter {
}

/**
 * Check if a given object implements the GetTwinLedgerEntryLedgerParameter interface.
 */
export function instanceOfGetTwinLedgerEntryLedgerParameter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTwinLedgerEntryLedgerParameterFromJSON(json: any): GetTwinLedgerEntryLedgerParameter {
    return GetTwinLedgerEntryLedgerParameterFromJSONTyped(json, false);
}

export function GetTwinLedgerEntryLedgerParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTwinLedgerEntryLedgerParameter {
    return json;
}

export function GetTwinLedgerEntryLedgerParameterToJSON(value?: GetTwinLedgerEntryLedgerParameter | null): any {
    return value;
}

