/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.03.01
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ServicesDatabaseDatabaseDetails,
    ServicesDatabaseDatabaseDetailsFromJSON,
    ServicesDatabaseDatabaseDetailsFromJSONTyped,
    ServicesDatabaseDatabaseDetailsToJSON,
} from './ServicesDatabaseDatabaseDetails';

/**
 * 
 * @export
 * @interface GetTimeseriesTablesResponseStats
 */
export interface GetTimeseriesTablesResponseStats {
    /**
     * Timeseries service status
     * @type {string}
     * @memberof GetTimeseriesTablesResponseStats
     */
    status?: GetTimeseriesTablesResponseStatsStatusEnum;
    /**
     * Database size in bytes
     * @type {number}
     * @memberof GetTimeseriesTablesResponseStats
     */
    databaseSize?: number;
}


/**
 * @export
 */
export const GetTimeseriesTablesResponseStatsStatusEnum = {
    Running: 'running',
    Pending: 'pending',
    Service: 'service'
} as const;
export type GetTimeseriesTablesResponseStatsStatusEnum = typeof GetTimeseriesTablesResponseStatsStatusEnum[keyof typeof GetTimeseriesTablesResponseStatsStatusEnum];


export function GetTimeseriesTablesResponseStatsFromJSON(json: any): GetTimeseriesTablesResponseStats {
    return GetTimeseriesTablesResponseStatsFromJSONTyped(json, false);
}

export function GetTimeseriesTablesResponseStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTimeseriesTablesResponseStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'databaseSize': !exists(json, 'database_size') ? undefined : json['database_size'],
    };
}

export function GetTimeseriesTablesResponseStatsToJSON(value?: GetTimeseriesTablesResponseStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'database_size': value.databaseSize,
    };
}

