/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetTimeseriesTablesResponseStats,
    GetTimeseriesTablesResponseStatsFromJSON,
    GetTimeseriesTablesResponseStatsFromJSONTyped,
    GetTimeseriesTablesResponseStatsToJSON,
} from './GetTimeseriesTablesResponseStats';
import {
    TimeseriesUserAccessCommand,
    TimeseriesUserAccessCommandFromJSON,
    TimeseriesUserAccessCommandFromJSONTyped,
    TimeseriesUserAccessCommandToJSON,
} from './TimeseriesUserAccessCommand';

/**
 * 
 * @export
 * @interface GetTimeseriesTablesResponse
 */
export interface GetTimeseriesTablesResponse {
    /**
     * 
     * @type {GetTimeseriesTablesResponseStats}
     * @memberof GetTimeseriesTablesResponse
     */
    stats: GetTimeseriesTablesResponseStats;
    /**
     * Users and their Timeseries access type
     * @type {{ [key: string]: TimeseriesUserAccessCommand; }}
     * @memberof GetTimeseriesTablesResponse
     */
    users?: { [key: string]: TimeseriesUserAccessCommand; };
    /**
     * Timeseries tables
     * @type {Array<string>}
     * @memberof GetTimeseriesTablesResponse
     */
    timeseries: Array<string>;
}

export function GetTimeseriesTablesResponseFromJSON(json: any): GetTimeseriesTablesResponse {
    return GetTimeseriesTablesResponseFromJSONTyped(json, false);
}

export function GetTimeseriesTablesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTimeseriesTablesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': GetTimeseriesTablesResponseStatsFromJSON(json['stats']),
        'users': !exists(json, 'users') ? undefined : (mapValues(json['users'], TimeseriesUserAccessCommandFromJSON)),
        'timeseries': json['timeseries'],
    };
}

export function GetTimeseriesTablesResponseToJSON(value?: GetTimeseriesTablesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': GetTimeseriesTablesResponseStatsToJSON(value.stats),
        'users': value.users === undefined ? undefined : (mapValues(value.users, TimeseriesUserAccessCommandToJSON)),
        'timeseries': value.timeseries,
    };
}

