/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdentityCreationCertificate,
    IdentityCreationCertificateFromJSON,
    IdentityCreationCertificateFromJSONTyped,
    IdentityCreationCertificateToJSON,
} from './IdentityCreationCertificate';

/**
 * 
 * @export
 * @interface IdentityRemovalPropertiesCreationCertificate
 */
export interface IdentityRemovalPropertiesCreationCertificate {
    /**
     * timestamp when Identity was created
     * @type {number}
     * @memberof IdentityRemovalPropertiesCreationCertificate
     */
    readonly createdTs?: number;
    /**
     * Account ID of creator
     * @type {string}
     * @memberof IdentityRemovalPropertiesCreationCertificate
     */
    readonly creator?: string;
}

export function IdentityRemovalPropertiesCreationCertificateFromJSON(json: any): IdentityRemovalPropertiesCreationCertificate {
    return IdentityRemovalPropertiesCreationCertificateFromJSONTyped(json, false);
}

export function IdentityRemovalPropertiesCreationCertificateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityRemovalPropertiesCreationCertificate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdTs': !exists(json, 'created_ts') ? undefined : json['created_ts'],
        'creator': !exists(json, 'creator') ? undefined : json['creator'],
    };
}

export function IdentityRemovalPropertiesCreationCertificateToJSON(value?: IdentityRemovalPropertiesCreationCertificate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

