/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdentityRemovalPropertiesCreationCertificate,
    IdentityRemovalPropertiesCreationCertificateFromJSON,
    IdentityRemovalPropertiesCreationCertificateFromJSONTyped,
    IdentityRemovalPropertiesCreationCertificateToJSON,
} from './IdentityRemovalPropertiesCreationCertificate';

/**
 * 
 * @export
 * @interface IdentityRemovalProperties
 */
export interface IdentityRemovalProperties {
    /**
     * UTC timestamp denoting validity of the Identity
     * @type {number}
     * @memberof IdentityRemovalProperties
     */
    validityTs?: number;
    /**
     * visibility of the Identity
     * @type {string}
     * @memberof IdentityRemovalProperties
     */
    visibility?: string;
    /**
     * UTC timestamp denoting validity of the Identity
     * @type {number}
     * @memberof IdentityRemovalProperties
     */
    updatedTs?: number;
    /**
     * 
     * @type {IdentityRemovalPropertiesCreationCertificate}
     * @memberof IdentityRemovalProperties
     */
    creationCertificate?: IdentityRemovalPropertiesCreationCertificate;
}

export function IdentityRemovalPropertiesFromJSON(json: any): IdentityRemovalProperties {
    return IdentityRemovalPropertiesFromJSONTyped(json, false);
}

export function IdentityRemovalPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityRemovalProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'updatedTs': !exists(json, 'updated_ts') ? undefined : json['updated_ts'],
        'creationCertificate': !exists(json, 'creation_certificate') ? undefined : IdentityRemovalPropertiesCreationCertificateFromJSON(json['creation_certificate']),
    };
}

export function IdentityRemovalPropertiesToJSON(value?: IdentityRemovalProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validity_ts': value.validityTs,
        'visibility': value.visibility,
        'updated_ts': value.updatedTs,
        'creation_certificate': IdentityRemovalPropertiesCreationCertificateToJSON(value.creationCertificate),
    };
}

