/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.05.02
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IndexColumns,
    IndexColumnsFromJSON,
    IndexColumnsFromJSONTyped,
    IndexColumnsToJSON,
} from './IndexColumns';
import {
    IndexTemplates,
    IndexTemplatesFromJSON,
    IndexTemplatesFromJSONTyped,
    IndexTemplatesToJSON,
} from './IndexTemplates';

/**
 * 
 * @export
 * @interface IndexTable
 */
export interface IndexTable {
    /**
     * Rule
     * @type {string}
     * @memberof IndexTable
     */
    rule: string;
    /**
     * 
     * @type {IndexColumns}
     * @memberof IndexTable
     */
    properties: IndexColumns;
    /**
     * 
     * @type {IndexTemplates}
     * @memberof IndexTable
     */
    templates: IndexTemplates;
}

export function IndexTableFromJSON(json: any): IndexTable {
    return IndexTableFromJSONTyped(json, false);
}

export function IndexTableFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexTable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rule': json['rule'],
        'properties': IndexColumnsFromJSON(json['properties']),
        'templates': IndexTemplatesFromJSON(json['templates']),
    };
}

export function IndexTableToJSON(value?: IndexTable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rule': value.rule,
        'properties': IndexColumnsToJSON(value.properties),
        'templates': IndexTemplatesToJSON(value.templates),
    };
}

