/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IndexColumns } from './IndexColumns';
import {
    IndexColumnsFromJSON,
    IndexColumnsFromJSONTyped,
    IndexColumnsToJSON,
} from './IndexColumns';
import type { IndexTemplates } from './IndexTemplates';
import {
    IndexTemplatesFromJSON,
    IndexTemplatesFromJSONTyped,
    IndexTemplatesToJSON,
} from './IndexTemplates';

/**
 * 
 * @export
 * @interface IndexTable
 */
export interface IndexTable {
    /**
     * Rule
     * @type {string}
     * @memberof IndexTable
     */
    rule: string;
    /**
     * 
     * @type {IndexColumns}
     * @memberof IndexTable
     */
    properties: IndexColumns;
    /**
     * 
     * @type {IndexTemplates}
     * @memberof IndexTable
     */
    templates: IndexTemplates;
}

/**
 * Check if a given object implements the IndexTable interface.
 */
export function instanceOfIndexTable(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rule" in value;
    isInstance = isInstance && "properties" in value;
    isInstance = isInstance && "templates" in value;

    return isInstance;
}

export function IndexTableFromJSON(json: any): IndexTable {
    return IndexTableFromJSONTyped(json, false);
}

export function IndexTableFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexTable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rule': json['rule'],
        'properties': IndexColumnsFromJSON(json['properties']),
        'templates': IndexTemplatesFromJSON(json['templates']),
    };
}

export function IndexTableToJSON(value?: IndexTable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rule': value.rule,
        'properties': IndexColumnsToJSON(value.properties),
        'templates': IndexTemplatesToJSON(value.templates),
    };
}

