/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.05.02
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexTableUpdate
 */
export interface IndexTableUpdate {
    /**
     * Rule
     * @type {string}
     * @memberof IndexTableUpdate
     */
    rule?: string;
}

export function IndexTableUpdateFromJSON(json: any): IndexTableUpdate {
    return IndexTableUpdateFromJSONTyped(json, false);
}

export function IndexTableUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexTableUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rule': !exists(json, 'rule') ? undefined : json['rule'],
    };
}

export function IndexTableUpdateToJSON(value?: IndexTableUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rule': value.rule,
    };
}

