/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LedgerAlias = {
    Personal: 'personal',
    Owner: 'owner',
    Creator: 'creator'
} as const;
export type LedgerAlias = typeof LedgerAlias[keyof typeof LedgerAlias];


export function LedgerAliasFromJSON(json: any): LedgerAlias {
    return LedgerAliasFromJSONTyped(json, false);
}

export function LedgerAliasFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerAlias {
    return json as LedgerAlias;
}

export function LedgerAliasToJSON(value?: LedgerAlias | null): any {
    return value as any;
}

