/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type LedgerEntriesHistoryEntriesValue
 * 
 * @export
 */
export type LedgerEntriesHistoryEntriesValue = { [key: string]: any; } | { [key: string]: string; };

export function LedgerEntriesHistoryEntriesValueFromJSON(json: any): LedgerEntriesHistoryEntriesValue {
    return LedgerEntriesHistoryEntriesValueFromJSONTyped(json, false);
}

export function LedgerEntriesHistoryEntriesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerEntriesHistoryEntriesValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...LedgerEntriesHistoryEntriesValueFromJSONTyped(json, true), ...LedgerEntriesHistoryEntriesValueFromJSONTyped(json, true) };
}

export function LedgerEntriesHistoryEntriesValueToJSON(value?: LedgerEntriesHistoryEntriesValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...LedgerEntriesHistoryEntriesValueToJSON(value), ...LedgerEntriesHistoryEntriesValueToJSON(value) };
}

