/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LedgerEntriesHistoryEntriesValue,
    LedgerEntriesHistoryEntriesValueFromJSON,
    LedgerEntriesHistoryEntriesValueFromJSONTyped,
    LedgerEntriesHistoryEntriesValueToJSON,
} from './LedgerEntriesHistoryEntriesValue';

/**
 * 
 * @export
 * @interface LedgerEntriesHistory
 */
export interface LedgerEntriesHistory {
    /**
     * 
     * @type {{ [key: string]: LedgerEntriesHistoryEntriesValue; }}
     * @memberof LedgerEntriesHistory
     */
    entries?: { [key: string]: LedgerEntriesHistoryEntriesValue; };
}

export function LedgerEntriesHistoryFromJSON(json: any): LedgerEntriesHistory {
    return LedgerEntriesHistoryFromJSONTyped(json, false);
}

export function LedgerEntriesHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerEntriesHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entries': !exists(json, 'entries') ? undefined : (mapValues(json['entries'], LedgerEntriesHistoryEntriesValueFromJSON)),
    };
}

export function LedgerEntriesHistoryToJSON(value?: LedgerEntriesHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entries': value.entries === undefined ? undefined : (mapValues(value.entries, LedgerEntriesHistoryEntriesValueToJSON)),
    };
}

