/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents Timeseries details
 * @export
 * @interface LedgerTimeseries
 */
export interface LedgerTimeseries {
    /**
     * 
     * @type {string}
     * @memberof LedgerTimeseries
     */
    measurement?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LedgerTimeseries
     */
    dimensions?: { [key: string]: string; };
}

export function LedgerTimeseriesFromJSON(json: any): LedgerTimeseries {
    return LedgerTimeseriesFromJSONTyped(json, false);
}

export function LedgerTimeseriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerTimeseries {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measurement': !exists(json, 'measurement') ? undefined : json['measurement'],
        'dimensions': !exists(json, 'dimensions') ? undefined : json['dimensions'],
    };
}

export function LedgerTimeseriesToJSON(value?: LedgerTimeseries | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measurement': value.measurement,
        'dimensions': value.dimensions,
    };
}

