/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewRoleStatement
 */
export interface NewRoleStatement {
    /**
     * allows or denies to perform an API operation
     * @type {string}
     * @memberof NewRoleStatement
     */
    effect?: NewRoleStatementEffectEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewRoleStatement
     */
    actions?: Array<string>;
}


/**
 * @export
 */
export const NewRoleStatementEffectEnum = {
    Allow: 'allow',
    Deny: 'deny'
} as const;
export type NewRoleStatementEffectEnum = typeof NewRoleStatementEffectEnum[keyof typeof NewRoleStatementEffectEnum];


/**
 * Check if a given object implements the NewRoleStatement interface.
 */
export function instanceOfNewRoleStatement(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NewRoleStatementFromJSON(json: any): NewRoleStatement {
    return NewRoleStatementFromJSONTyped(json, false);
}

export function NewRoleStatementFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewRoleStatement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'effect': !exists(json, 'effect') ? undefined : json['effect'],
        'actions': !exists(json, 'actions') ? undefined : json['actions'],
    };
}

export function NewRoleStatementToJSON(value?: NewRoleStatement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'effect': value.effect,
        'actions': value.actions,
    };
}

