/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.07.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NewTokenResponse
 */
export interface NewTokenResponse {
  /**
   * Newly created Token
   * @type {string}
   * @memberof NewTokenResponse
   */
  userToken?: string;
  /**
   *
   * @type {string}
   * @memberof NewTokenResponse
   */
  options?: NewTokenResponseOptionsEnum;
  /**
   * UTC timestamp denoting validity of the Token
   * @type {number}
   * @memberof NewTokenResponse
   */
  validityTs?: number;
}

/**
 * @export
 */
export const NewTokenResponseOptionsEnum = {
  Refresh: "REFRESH",
  Create: "CREATE",
} as const;
export type NewTokenResponseOptionsEnum =
  typeof NewTokenResponseOptionsEnum[keyof typeof NewTokenResponseOptionsEnum];

export function NewTokenResponseFromJSON(json: any): NewTokenResponse {
  return NewTokenResponseFromJSONTyped(json, false);
}

export function NewTokenResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): NewTokenResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userToken: !exists(json, "user_token") ? undefined : json["user_token"],
    options: !exists(json, "options") ? undefined : json["options"],
    validityTs: !exists(json, "validity_ts") ? undefined : json["validity_ts"],
  };
}

export function NewTokenResponseToJSON(value?: NewTokenResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user_token: value.userToken,
    options: value.options,
    validity_ts: value.validityTs,
  };
}
