/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchIdentityProperties
 */
export interface PatchIdentityProperties {
    /**
     * UTC timestamp denoting validity of the Identity
     * @type {number}
     * @memberof PatchIdentityProperties
     */
    validityTs?: number;
    /**
     * visibility of the Identity
     * @type {string}
     * @memberof PatchIdentityProperties
     */
    visibility?: string;
}

export function PatchIdentityPropertiesFromJSON(json: any): PatchIdentityProperties {
    return PatchIdentityPropertiesFromJSONTyped(json, false);
}

export function PatchIdentityPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchIdentityProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
    };
}

export function PatchIdentityPropertiesToJSON(value?: PatchIdentityProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validity_ts': value.validityTs,
        'visibility': value.visibility,
    };
}

