/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PostForeignLedgerEntriesValue,
    PostForeignLedgerEntriesValueFromJSON,
    PostForeignLedgerEntriesValueFromJSONTyped,
    PostForeignLedgerEntriesValueToJSON,
} from './PostForeignLedgerEntriesValue';

/**
 * 
 * @export
 * @interface PatchForeignLedger
 */
export interface PatchForeignLedger {
    /**
     * 
     * @type {{ [key: string]: PostForeignLedgerEntriesValue; }}
     * @memberof PatchForeignLedger
     */
    entries?: { [key: string]: PostForeignLedgerEntriesValue; };
}

export function PatchForeignLedgerFromJSON(json: any): PatchForeignLedger {
    return PatchForeignLedgerFromJSONTyped(json, false);
}

export function PatchForeignLedgerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchForeignLedger {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entries': !exists(json, 'entries') ? undefined : (mapValues(json['entries'], PostForeignLedgerEntriesValueFromJSON)),
    };
}

export function PatchForeignLedgerToJSON(value?: PatchForeignLedger | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entries': value.entries === undefined ? undefined : (mapValues(value.entries, PostForeignLedgerEntriesValueToJSON)),
    };
}

