/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ReferenceEntry | ValueEntry,
    ReferenceEntry | ValueEntryFromJSON,
    ReferenceEntry | ValueEntryFromJSONTyped,
    ReferenceEntry | ValueEntryToJSON,
} from './ReferenceEntry | ValueEntry';

/**
 * 
 * @export
 * @interface PostLedgerEntries
 */
export interface PostLedgerEntries {
    /**
     * 
     * @type {{ [key: string]: ReferenceEntry | ValueEntry; }}
     * @memberof PostLedgerEntries
     */
    entries?: { [key: string]: ReferenceEntry | ValueEntry; };
}

export function PostLedgerEntriesFromJSON(json: any): PostLedgerEntries {
    return PostLedgerEntriesFromJSONTyped(json, false);
}

export function PostLedgerEntriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLedgerEntries {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entries': !exists(json, 'entries') ? undefined : (mapValues(json['entries'], ReferenceEntry | ValueEntryFromJSON)),
    };
}

export function PostLedgerEntriesToJSON(value?: PostLedgerEntries | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entries': value.entries === undefined ? undefined : (mapValues(value.entries, ReferenceEntry | ValueEntryToJSON)),
    };
}

