/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostNewUser
 */
export interface PostNewUser {
    /**
     * Optional User name (doesn't have to be unique), must conform to '^[0-9A-Za-z][0-9A-Za-z_ \-]{0,30}[0-9A-Za-z]*$'
     * @type {string}
     * @memberof PostNewUser
     */
    name?: string;
    /**
     * Role UUID
     * @type {string}
     * @memberof PostNewUser
     */
    role: string;
    /**
     * Custom defined variables
     * @type {{ [key: string]: string; }}
     * @memberof PostNewUser
     */
    description?: { [key: string]: string; };
}

export function PostNewUserFromJSON(json: any): PostNewUser {
    return PostNewUserFromJSONTyped(json, false);
}

export function PostNewUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostNewUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'role': json['role'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function PostNewUserToJSON(value?: PostNewUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'role': value.role,
        'description': value.description,
    };
}

