/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostNewToken
 */
export interface PostNewToken {
    /**
     * Custom defined variables
     * @type {{ [key: string]: string; }}
     * @memberof PostNewToken
     */
    ttDict?: { [key: string]: string; };
    /**
     * Token refresh/creation rules
     * @type {string}
     * @memberof PostNewToken
     */
    options?: PostNewTokenOptionsEnum;
    /**
     * UTC timestamp denoting validity of the Token
     * @type {number}
     * @memberof PostNewToken
     */
    validityTs?: number;
}


/**
 * @export
 */
export const PostNewTokenOptionsEnum = {
    Refresh: 'REFRESH',
    Create: 'CREATE'
} as const;
export type PostNewTokenOptionsEnum = typeof PostNewTokenOptionsEnum[keyof typeof PostNewTokenOptionsEnum];


export function PostNewTokenFromJSON(json: any): PostNewToken {
    return PostNewTokenFromJSONTyped(json, false);
}

export function PostNewTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostNewToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ttDict': !exists(json, 'tt_dict') ? undefined : json['tt_dict'],
        'options': !exists(json, 'options') ? undefined : json['options'],
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
    };
}

export function PostNewTokenToJSON(value?: PostNewToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tt_dict': value.ttDict,
        'options': value.options,
        'validity_ts': value.validityTs,
    };
}

