/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdentityProperties,
    IdentityPropertiesFromJSON,
    IdentityPropertiesFromJSONTyped,
    IdentityPropertiesToJSON,
} from './IdentityProperties';

/**
 * 
 * @export
 * @interface PostTwinIdentities
 */
export interface PostTwinIdentities {
    /**
     * 
     * @type {{ [key: string]: IdentityProperties; }}
     * @memberof PostTwinIdentities
     */
    identities?: { [key: string]: IdentityProperties; };
}

export function PostTwinIdentitiesFromJSON(json: any): PostTwinIdentities {
    return PostTwinIdentitiesFromJSONTyped(json, false);
}

export function PostTwinIdentitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTwinIdentities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identities': !exists(json, 'identities') ? undefined : (mapValues(json['identities'], IdentityPropertiesFromJSON)),
    };
}

export function PostTwinIdentitiesToJSON(value?: PostTwinIdentities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identities': value.identities === undefined ? undefined : (mapValues(value.identities, IdentityPropertiesToJSON)),
    };
}

