/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ValueEntry,
    ValueEntryFromJSON,
    ValueEntryFromJSONTyped,
    ValueEntryToJSON,
} from './ValueEntry';

/**
 * 
 * @export
 * @interface PostForeignLedgerEntriesValue
 */
export interface PostForeignLedgerEntriesValue {
    /**
     * value for corresponding Key
     * @type {string}
     * @memberof PostForeignLedgerEntriesValue
     */
    value?: string;
    /**
     * type of value
     * @type {string}
     * @memberof PostForeignLedgerEntriesValue
     */
    type?: PostForeignLedgerEntriesValueTypeEnum;
    /**
     * Visibility of the Entry
     * @type {string}
     * @memberof PostForeignLedgerEntriesValue
     */
    visibility?: string;
    /**
     * UTC timestamp denoting when the Entry was created
     * @type {number}
     * @memberof PostForeignLedgerEntriesValue
     */
    readonly entryCreatedTs?: number;
    /**
     * UTC timestamp denoting when the Entry was last updated
     * @type {number}
     * @memberof PostForeignLedgerEntriesValue
     */
    readonly entryUpdatedTs?: number;
    /**
     * UTC timestamp denoting when the Entry's value was last changed
     * @type {number}
     * @memberof PostForeignLedgerEntriesValue
     */
    readonly valueChangedTs?: number;
}


/**
 * @export
 */
export const PostForeignLedgerEntriesValueTypeEnum = {
    String: 'string',
    Integer: 'integer',
    Datetime: 'datetime'
} as const;
export type PostForeignLedgerEntriesValueTypeEnum = typeof PostForeignLedgerEntriesValueTypeEnum[keyof typeof PostForeignLedgerEntriesValueTypeEnum];


export function PostForeignLedgerEntriesValueFromJSON(json: any): PostForeignLedgerEntriesValue {
    return PostForeignLedgerEntriesValueFromJSONTyped(json, false);
}

export function PostForeignLedgerEntriesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostForeignLedgerEntriesValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'entryCreatedTs': !exists(json, 'entry_created_ts') ? undefined : json['entry_created_ts'],
        'entryUpdatedTs': !exists(json, 'entry_updated_ts') ? undefined : json['entry_updated_ts'],
        'valueChangedTs': !exists(json, 'value_changed_ts') ? undefined : json['value_changed_ts'],
    };
}

export function PostForeignLedgerEntriesValueToJSON(value?: PostForeignLedgerEntriesValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'type': value.type,
        'visibility': value.visibility,
    };
}

