/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PostTwinIdentitiesIdentities,
    PostTwinIdentitiesIdentitiesFromJSON,
    PostTwinIdentitiesIdentitiesFromJSONTyped,
    PostTwinIdentitiesIdentitiesToJSON,
} from './PostTwinIdentitiesIdentities';

/**
 * 
 * @export
 * @interface PostTwinIdentities
 */
export interface PostTwinIdentities {
    /**
     * 
     * @type {PostTwinIdentitiesIdentities}
     * @memberof PostTwinIdentities
     */
    identities?: PostTwinIdentitiesIdentities;
}

export function PostTwinIdentitiesFromJSON(json: any): PostTwinIdentities {
    return PostTwinIdentitiesFromJSONTyped(json, false);
}

export function PostTwinIdentitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTwinIdentities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identities': !exists(json, 'identities') ? undefined : PostTwinIdentitiesIdentitiesFromJSON(json['identities']),
    };
}

export function PostTwinIdentitiesToJSON(value?: PostTwinIdentities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identities': PostTwinIdentitiesIdentitiesToJSON(value.identities),
    };
}

