/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdentityProperties,
    IdentityPropertiesFromJSON,
    IdentityPropertiesFromJSONTyped,
    IdentityPropertiesToJSON,
} from './IdentityProperties';

/**
 * 
 * @export
 * @interface PostTwinIdentitiesIdentities
 */
export interface PostTwinIdentitiesIdentities {
    /**
     * 
     * @type {IdentityProperties}
     * @memberof PostTwinIdentitiesIdentities
     */
    additionalProperties?: IdentityProperties;
}

export function PostTwinIdentitiesIdentitiesFromJSON(json: any): PostTwinIdentitiesIdentities {
    return PostTwinIdentitiesIdentitiesFromJSONTyped(json, false);
}

export function PostTwinIdentitiesIdentitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTwinIdentitiesIdentities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'additionalProperties': !exists(json, 'additionalProperties') ? undefined : IdentityPropertiesFromJSON(json['additionalProperties']),
    };
}

export function PostTwinIdentitiesIdentitiesToJSON(value?: PostTwinIdentitiesIdentities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'additionalProperties': IdentityPropertiesToJSON(value.additionalProperties),
    };
}

