/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.07.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PostRefreshToken
 */
export interface PostRefreshToken {
  /**
   * UTC timestamp denoting validity of the Token
   * @type {number}
   * @memberof PostRefreshToken
   */
  validityTs?: number;
}

export function PostRefreshTokenFromJSON(json: any): PostRefreshToken {
  return PostRefreshTokenFromJSONTyped(json, false);
}

export function PostRefreshTokenFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostRefreshToken {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    validityTs: !exists(json, "validity_ts") ? undefined : json["validity_ts"],
  };
}

export function PostRefreshTokenToJSON(value?: PostRefreshToken | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    validity_ts: value.validityTs,
  };
}
