/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReferenceEntryTimeseries
 */
export interface ReferenceEntryTimeseries {
    /**
     * 
     * @type {string}
     * @memberof ReferenceEntryTimeseries
     */
    measurement?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ReferenceEntryTimeseries
     */
    dimensions?: { [key: string]: string; };
}

/**
 * Check if a given object implements the ReferenceEntryTimeseries interface.
 */
export function instanceOfReferenceEntryTimeseries(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceEntryTimeseriesFromJSON(json: any): ReferenceEntryTimeseries {
    return ReferenceEntryTimeseriesFromJSONTyped(json, false);
}

export function ReferenceEntryTimeseriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntryTimeseries {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measurement': !exists(json, 'measurement') ? undefined : json['measurement'],
        'dimensions': !exists(json, 'dimensions') ? undefined : json['dimensions'],
    };
}

export function ReferenceEntryTimeseriesToJSON(value?: ReferenceEntryTimeseries | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measurement': value.measurement,
        'dimensions': value.dimensions,
    };
}

