/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Database statistics and information
 * @export
 * @interface ServicesDatabaseDatabaseDetails
 */
export interface ServicesDatabaseDatabaseDetails {
    /**
     * Timeseries service status
     * @type {string}
     * @memberof ServicesDatabaseDatabaseDetails
     */
    status?: ServicesDatabaseDatabaseDetailsStatusEnum;
    /**
     * Database size in bytes
     * @type {number}
     * @memberof ServicesDatabaseDatabaseDetails
     */
    databaseSize?: number;
}


/**
 * @export
 */
export const ServicesDatabaseDatabaseDetailsStatusEnum = {
    Running: 'running',
    Pending: 'pending',
    Service: 'service'
} as const;
export type ServicesDatabaseDatabaseDetailsStatusEnum = typeof ServicesDatabaseDatabaseDetailsStatusEnum[keyof typeof ServicesDatabaseDatabaseDetailsStatusEnum];


/**
 * Check if a given object implements the ServicesDatabaseDatabaseDetails interface.
 */
export function instanceOfServicesDatabaseDatabaseDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServicesDatabaseDatabaseDetailsFromJSON(json: any): ServicesDatabaseDatabaseDetails {
    return ServicesDatabaseDatabaseDetailsFromJSONTyped(json, false);
}

export function ServicesDatabaseDatabaseDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesDatabaseDatabaseDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'databaseSize': !exists(json, 'database_size') ? undefined : json['database_size'],
    };
}

export function ServicesDatabaseDatabaseDetailsToJSON(value?: ServicesDatabaseDatabaseDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'database_size': value.databaseSize,
    };
}

