/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Timeseries database column type
 * @export
 */
export const ServicesDatabaseColumnType = {
    Int: 'int',
    Bigint: 'bigint',
    Smallint: 'smallint',
    Integer: 'integer',
    Numeric: 'numeric',
    Real: 'real',
    DoublePrecision: 'double precision',
    Json: 'json',
    Jsonb: 'jsonb',
    Bool: 'bool',
    Boolean: 'boolean',
    CharacterVarying: 'character varying',
    Varchar: 'varchar',
    Text: 'text',
    Date: 'date',
    Time: 'time',
    Timestamp: 'timestamp',
    Timestamptz: 'timestamptz',
    Uuid: 'uuid',
    Interval: 'interval',
    Geography: 'geography',
    Geometry: 'geometry'
} as const;
export type ServicesDatabaseColumnType = typeof ServicesDatabaseColumnType[keyof typeof ServicesDatabaseColumnType];


export function ServicesDatabaseColumnTypeFromJSON(json: any): ServicesDatabaseColumnType {
    return ServicesDatabaseColumnTypeFromJSONTyped(json, false);
}

export function ServicesDatabaseColumnTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesDatabaseColumnType {
    return json as ServicesDatabaseColumnType;
}

export function ServicesDatabaseColumnTypeToJSON(value?: ServicesDatabaseColumnType | null): any {
    return value as any;
}

