/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServicesDatabaseUserAccessRights = {
    Read: 'read',
    Write: 'write',
    Disable: 'disable'
} as const;
export type ServicesDatabaseUserAccessRights = typeof ServicesDatabaseUserAccessRights[keyof typeof ServicesDatabaseUserAccessRights];


export function ServicesDatabaseUserAccessRightsFromJSON(json: any): ServicesDatabaseUserAccessRights {
    return ServicesDatabaseUserAccessRightsFromJSONTyped(json, false);
}

export function ServicesDatabaseUserAccessRightsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesDatabaseUserAccessRights {
    return json as ServicesDatabaseUserAccessRights;
}

export function ServicesDatabaseUserAccessRightsToJSON(value?: ServicesDatabaseUserAccessRights | null): any {
    return value as any;
}

