/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StickersResponseAccountsValueValue,
    StickersResponseAccountsValueValueFromJSON,
    StickersResponseAccountsValueValueFromJSONTyped,
    StickersResponseAccountsValueValueToJSON,
} from './StickersResponseAccountsValueValue';

/**
 * 
 * @export
 * @interface StickersResponse
 */
export interface StickersResponse {
    /**
     * 
     * @type {{ [key: string]: { [key: string]: StickersResponseAccountsValueValue; }; }}
     * @memberof StickersResponse
     */
    accounts?: { [key: string]: { [key: string]: StickersResponseAccountsValueValue; }; };
}

export function StickersResponseFromJSON(json: any): StickersResponse {
    return StickersResponseFromJSONTyped(json, false);
}

export function StickersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StickersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accounts': !exists(json, 'accounts') ? undefined : json['accounts'],
    };
}

export function StickersResponseToJSON(value?: StickersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accounts': value.accounts,
    };
}

