/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.07.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StickersListStickersInner
 */
export interface StickersListStickersInner {
  /**
   *
   * @type {string}
   * @memberof StickersListStickersInner
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof StickersListStickersInner
   */
  account?: string;
  /**
   *
   * @type {string}
   * @memberof StickersListStickersInner
   */
  twin?: string;
  /**
   *
   * @type {string}
   * @memberof StickersListStickersInner
   */
  message?: string;
  /**
   *
   * @type {number}
   * @memberof StickersListStickersInner
   */
  validityTs?: number;
  /**
   *
   * @type {number}
   * @memberof StickersListStickersInner
   */
  createdTs?: number;
  /**
   *
   * @type {number}
   * @memberof StickersListStickersInner
   */
  updatedTs?: number;
}

export function StickersListStickersInnerFromJSON(
  json: any
): StickersListStickersInner {
  return StickersListStickersInnerFromJSONTyped(json, false);
}

export function StickersListStickersInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StickersListStickersInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    color: !exists(json, "color") ? undefined : json["color"],
    account: !exists(json, "account") ? undefined : json["account"],
    twin: !exists(json, "twin") ? undefined : json["twin"],
    message: !exists(json, "message") ? undefined : json["message"],
    validityTs: !exists(json, "validity_ts") ? undefined : json["validity_ts"],
    createdTs: !exists(json, "created_ts") ? undefined : json["created_ts"],
    updatedTs: !exists(json, "updated_ts") ? undefined : json["updated_ts"],
  };
}

export function StickersListStickersInnerToJSON(
  value?: StickersListStickersInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    color: value.color,
    account: value.account,
    twin: value.twin,
    message: value.message,
    validity_ts: value.validityTs,
    created_ts: value.createdTs,
    updated_ts: value.updatedTs,
  };
}
