/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TableError
 */
export interface TableError {
    /**
     * 
     * @type {string}
     * @memberof TableError
     */
    error: string;
}

/**
 * Check if a given object implements the TableError interface.
 */
export function instanceOfTableError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function TableErrorFromJSON(json: any): TableError {
    return TableErrorFromJSONTyped(json, false);
}

export function TableErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function TableErrorToJSON(value?: TableError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

