/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TimeseriesUserAccessCommand,
    TimeseriesUserAccessCommandFromJSON,
    TimeseriesUserAccessCommandFromJSONTyped,
    TimeseriesUserAccessCommandToJSON,
} from './TimeseriesUserAccessCommand';

/**
 * 
 * @export
 * @interface TimeseriesUsersAccess
 */
export interface TimeseriesUsersAccess {
    /**
     * Users and their Timeseries access type
     * @type {{ [key: string]: TimeseriesUserAccessCommand; }}
     * @memberof TimeseriesUsersAccess
     */
    users?: { [key: string]: TimeseriesUserAccessCommand; };
}

export function TimeseriesUsersAccessFromJSON(json: any): TimeseriesUsersAccess {
    return TimeseriesUsersAccessFromJSONTyped(json, false);
}

export function TimeseriesUsersAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesUsersAccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': !exists(json, 'users') ? undefined : (mapValues(json['users'], TimeseriesUserAccessCommandFromJSON)),
    };
}

export function TimeseriesUsersAccessToJSON(value?: TimeseriesUsersAccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': value.users === undefined ? undefined : (mapValues(value.users, TimeseriesUserAccessCommandToJSON)),
    };
}

