/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeseriesTableError
 */
export interface TimeseriesTableError {
    /**
     * 
     * @type {string}
     * @memberof TimeseriesTableError
     */
    error: string;
}

export function TimeseriesTableErrorFromJSON(json: any): TimeseriesTableError {
    return TimeseriesTableErrorFromJSONTyped(json, false);
}

export function TimeseriesTableErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesTableError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function TimeseriesTableErrorToJSON(value?: TimeseriesTableError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

