/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TimeseriesColumnType,
    TimeseriesColumnTypeFromJSON,
    TimeseriesColumnTypeFromJSONTyped,
    TimeseriesColumnTypeToJSON,
} from './TimeseriesColumnType';

/**
 * Timeseries table columns definition
 * @export
 * @interface TimeseriesColumns
 */
export interface TimeseriesColumns {
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeseriesColumns
     */
    names?: Array<string>;
    /**
     * 
     * @type {Array<TimeseriesColumnType>}
     * @memberof TimeseriesColumns
     */
    types?: Array<TimeseriesColumnType>;
}

export function TimeseriesColumnsFromJSON(json: any): TimeseriesColumns {
    return TimeseriesColumnsFromJSONTyped(json, false);
}

export function TimeseriesColumnsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesColumns {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'names': !exists(json, 'names') ? undefined : json['names'],
        'types': !exists(json, 'types') ? undefined : ((json['types'] as Array<any>).map(TimeseriesColumnTypeFromJSON)),
    };
}

export function TimeseriesColumnsToJSON(value?: TimeseriesColumns | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'names': value.names,
        'types': value.types === undefined ? undefined : ((value.types as Array<any>).map(TimeseriesColumnTypeToJSON)),
    };
}

