/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LedgerTimeseries,
    LedgerTimeseriesFromJSON,
    LedgerTimeseriesFromJSONTyped,
    LedgerTimeseriesToJSON,
} from './LedgerTimeseries';
import {
    TimeseriesColumns,
    TimeseriesColumnsFromJSON,
    TimeseriesColumnsFromJSONTyped,
    TimeseriesColumnsToJSON,
} from './TimeseriesColumns';
import {
    TimeseriesDatabaseTableDetails,
    TimeseriesDatabaseTableDetailsFromJSON,
    TimeseriesDatabaseTableDetailsFromJSONTyped,
    TimeseriesDatabaseTableDetailsToJSON,
} from './TimeseriesDatabaseTableDetails';

/**
 * 
 * @export
 * @interface TimeseriesTableResponse
 */
export interface TimeseriesTableResponse {
    /**
     * 
     * @type {TimeseriesDatabaseTableDetails}
     * @memberof TimeseriesTableResponse
     */
    stats: TimeseriesDatabaseTableDetails | null;
    /**
     * 
     * @type {TimeseriesColumns}
     * @memberof TimeseriesTableResponse
     */
    dimensions: TimeseriesColumns;
    /**
     * 
     * @type {TimeseriesColumns}
     * @memberof TimeseriesTableResponse
     */
    measurements: TimeseriesColumns;
    /**
     * 
     * @type {LedgerTimeseries}
     * @memberof TimeseriesTableResponse
     */
    defaults?: LedgerTimeseries;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesTableResponse
     */
    retention?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesTableResponse
     */
    chunk?: string | null;
}

export function TimeseriesTableResponseFromJSON(json: any): TimeseriesTableResponse {
    return TimeseriesTableResponseFromJSONTyped(json, false);
}

export function TimeseriesTableResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesTableResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': TimeseriesDatabaseTableDetailsFromJSON(json['stats']),
        'dimensions': TimeseriesColumnsFromJSON(json['dimensions']),
        'measurements': TimeseriesColumnsFromJSON(json['measurements']),
        'defaults': !exists(json, 'defaults') ? undefined : LedgerTimeseriesFromJSON(json['defaults']),
        'retention': !exists(json, 'retention') ? undefined : json['retention'],
        'chunk': !exists(json, 'chunk') ? undefined : json['chunk'],
    };
}

export function TimeseriesTableResponseToJSON(value?: TimeseriesTableResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': TimeseriesDatabaseTableDetailsToJSON(value.stats),
        'dimensions': TimeseriesColumnsToJSON(value.dimensions),
        'measurements': TimeseriesColumnsToJSON(value.measurements),
        'defaults': LedgerTimeseriesToJSON(value.defaults),
        'retention': value.retention,
        'chunk': value.chunk,
    };
}

