/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LedgerTimeseries,
    LedgerTimeseriesFromJSON,
    LedgerTimeseriesFromJSONTyped,
    LedgerTimeseriesToJSON,
} from './LedgerTimeseries';

/**
 * 
 * @export
 * @interface TimeseriesTableUpdate
 */
export interface TimeseriesTableUpdate {
    /**
     * 
     * @type {LedgerTimeseries}
     * @memberof TimeseriesTableUpdate
     */
    defaults?: LedgerTimeseries;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesTableUpdate
     */
    retention?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesTableUpdate
     */
    chunk?: string | null;
}

export function TimeseriesTableUpdateFromJSON(json: any): TimeseriesTableUpdate {
    return TimeseriesTableUpdateFromJSONTyped(json, false);
}

export function TimeseriesTableUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesTableUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaults': !exists(json, 'defaults') ? undefined : LedgerTimeseriesFromJSON(json['defaults']),
        'retention': !exists(json, 'retention') ? undefined : json['retention'],
        'chunk': !exists(json, 'chunk') ? undefined : json['chunk'],
    };
}

export function TimeseriesTableUpdateToJSON(value?: TimeseriesTableUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaults': LedgerTimeseriesToJSON(value.defaults),
        'retention': value.retention,
        'chunk': value.chunk,
    };
}

