/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TimeseriesTable | TimeseriesTableError,
    TimeseriesTable | TimeseriesTableErrorFromJSON,
    TimeseriesTable | TimeseriesTableErrorFromJSONTyped,
    TimeseriesTable | TimeseriesTableErrorToJSON,
} from './TimeseriesTable | TimeseriesTableError';

/**
 * 
 * @export
 * @interface TimeseriesTablesResponse
 */
export interface TimeseriesTablesResponse {
    /**
     * 
     * @type {{ [key: string]: TimeseriesTable | TimeseriesTableError; }}
     * @memberof TimeseriesTablesResponse
     */
    timeseries?: { [key: string]: TimeseriesTable | TimeseriesTableError; };
}

export function TimeseriesTablesResponseFromJSON(json: any): TimeseriesTablesResponse {
    return TimeseriesTablesResponseFromJSONTyped(json, false);
}

export function TimeseriesTablesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesTablesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeseries': !exists(json, 'timeseries') ? undefined : (mapValues(json['timeseries'], TimeseriesTable | TimeseriesTableErrorFromJSON)),
    };
}

export function TimeseriesTablesResponseToJSON(value?: TimeseriesTablesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeseries': value.timeseries === undefined ? undefined : (mapValues(value.timeseries, TimeseriesTable | TimeseriesTableErrorToJSON)),
    };
}

