/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TimeseriesUserAccessCommand {
    Read = 'read',
    Write = 'write',
    Disable = 'disable'
}

export function TimeseriesUserAccessCommandFromJSON(json: any): TimeseriesUserAccessCommand {
    return TimeseriesUserAccessCommandFromJSONTyped(json, false);
}

export function TimeseriesUserAccessCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesUserAccessCommand {
    return json as TimeseriesUserAccessCommand;
}

export function TimeseriesUserAccessCommandToJSON(value?: TimeseriesUserAccessCommand | null): any {
    return value as any;
}

