/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Timeseries database column type
 * @export
 */
export const TimeseriesColumnType = {
    Int: 'int',
    Bigint: 'bigint',
    Smallint: 'smallint',
    Integer: 'integer',
    Numeric: 'numeric',
    Real: 'real',
    DoublePrecision: 'double precision',
    Json: 'json',
    Jsonb: 'jsonb',
    Bool: 'bool',
    Boolean: 'boolean',
    CharacterVarying: 'character varying',
    Varchar: 'varchar',
    Text: 'text',
    Date: 'date',
    Time: 'time',
    Interval: 'interval',
    Timestamp: 'timestamp',
    Timestamptz: 'timestamptz',
    Uuid: 'uuid'
} as const;
export type TimeseriesColumnType = typeof TimeseriesColumnType[keyof typeof TimeseriesColumnType];


export function TimeseriesColumnTypeFromJSON(json: any): TimeseriesColumnType {
    return TimeseriesColumnTypeFromJSONTyped(json, false);
}

export function TimeseriesColumnTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesColumnType {
    return json as TimeseriesColumnType;
}

export function TimeseriesColumnTypeToJSON(value?: TimeseriesColumnType | null): any {
    return value as any;
}

