/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.03.01
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IndexColumns,
    IndexColumnsFromJSON,
    IndexColumnsFromJSONTyped,
    IndexColumnsToJSON,
} from './IndexColumns';
import {
    IndexTableResponse,
    IndexTableResponseFromJSON,
    IndexTableResponseFromJSONTyped,
    IndexTableResponseToJSON,
} from './IndexTableResponse';
import {
    IndexTableResponseStats,
    IndexTableResponseStatsFromJSON,
    IndexTableResponseStatsFromJSONTyped,
    IndexTableResponseStatsToJSON,
} from './IndexTableResponseStats';
import {
    IndexTemplates,
    IndexTemplatesFromJSON,
    IndexTemplatesFromJSONTyped,
    IndexTemplatesToJSON,
} from './IndexTemplates';

/**
 * 
 * @export
 * @interface TruncateIndexesTable200Response
 */
export interface TruncateIndexesTable200Response {
    /**
     * 
     * @type {IndexTableResponseStats}
     * @memberof TruncateIndexesTable200Response
     */
    stats: IndexTableResponseStats;
    /**
     * Rule
     * @type {string}
     * @memberof TruncateIndexesTable200Response
     */
    rule: string;
    /**
     * 
     * @type {IndexColumns}
     * @memberof TruncateIndexesTable200Response
     */
    properties: IndexColumns;
    /**
     * 
     * @type {IndexTemplates}
     * @memberof TruncateIndexesTable200Response
     */
    templates: IndexTemplates;
}

export function TruncateIndexesTable200ResponseFromJSON(json: any): TruncateIndexesTable200Response {
    return TruncateIndexesTable200ResponseFromJSONTyped(json, false);
}

export function TruncateIndexesTable200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TruncateIndexesTable200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': IndexTableResponseStatsFromJSON(json['stats']),
        'rule': json['rule'],
        'properties': IndexColumnsFromJSON(json['properties']),
        'templates': IndexTemplatesFromJSON(json['templates']),
    };
}

export function TruncateIndexesTable200ResponseToJSON(value?: TruncateIndexesTable200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': IndexTableResponseStatsToJSON(value.stats),
        'rule': value.rule,
        'properties': IndexColumnsToJSON(value.properties),
        'templates': IndexTemplatesToJSON(value.templates),
    };
}

