/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.03.01
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LedgerEntryTimeseries,
    LedgerEntryTimeseriesFromJSON,
    LedgerEntryTimeseriesFromJSONTyped,
    LedgerEntryTimeseriesToJSON,
} from './LedgerEntryTimeseries';
import {
    TimeseriesColumns,
    TimeseriesColumnsFromJSON,
    TimeseriesColumnsFromJSONTyped,
    TimeseriesColumnsToJSON,
} from './TimeseriesColumns';
import {
    TimeseriesTableResponse,
    TimeseriesTableResponseFromJSON,
    TimeseriesTableResponseFromJSONTyped,
    TimeseriesTableResponseToJSON,
} from './TimeseriesTableResponse';
import {
    TimeseriesTableResponseStats,
    TimeseriesTableResponseStatsFromJSON,
    TimeseriesTableResponseStatsFromJSONTyped,
    TimeseriesTableResponseStatsToJSON,
} from './TimeseriesTableResponseStats';

/**
 * 
 * @export
 * @interface TruncateTimeseriesTable200Response
 */
export interface TruncateTimeseriesTable200Response {
    /**
     * 
     * @type {TimeseriesTableResponseStats}
     * @memberof TruncateTimeseriesTable200Response
     */
    stats: TimeseriesTableResponseStats;
    /**
     * 
     * @type {TimeseriesColumns}
     * @memberof TruncateTimeseriesTable200Response
     */
    dimensions: TimeseriesColumns;
    /**
     * 
     * @type {TimeseriesColumns}
     * @memberof TruncateTimeseriesTable200Response
     */
    measurements: TimeseriesColumns;
    /**
     * 
     * @type {LedgerEntryTimeseries}
     * @memberof TruncateTimeseriesTable200Response
     */
    defaults?: LedgerEntryTimeseries;
    /**
     * 
     * @type {string}
     * @memberof TruncateTimeseriesTable200Response
     */
    retention?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TruncateTimeseriesTable200Response
     */
    chunk?: string | null;
}

export function TruncateTimeseriesTable200ResponseFromJSON(json: any): TruncateTimeseriesTable200Response {
    return TruncateTimeseriesTable200ResponseFromJSONTyped(json, false);
}

export function TruncateTimeseriesTable200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TruncateTimeseriesTable200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': TimeseriesTableResponseStatsFromJSON(json['stats']),
        'dimensions': TimeseriesColumnsFromJSON(json['dimensions']),
        'measurements': TimeseriesColumnsFromJSON(json['measurements']),
        'defaults': !exists(json, 'defaults') ? undefined : LedgerEntryTimeseriesFromJSON(json['defaults']),
        'retention': !exists(json, 'retention') ? undefined : json['retention'],
        'chunk': !exists(json, 'chunk') ? undefined : json['chunk'],
    };
}

export function TruncateTimeseriesTable200ResponseToJSON(value?: TruncateTimeseriesTable200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': TimeseriesTableResponseStatsToJSON(value.stats),
        'dimensions': TimeseriesColumnsToJSON(value.dimensions),
        'measurements': TimeseriesColumnsToJSON(value.measurements),
        'defaults': LedgerEntryTimeseriesToJSON(value.defaults),
        'retention': value.retention,
        'chunk': value.chunk,
    };
}

