/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.07.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface TwinCreationCertificate
 */
export interface TwinCreationCertificate {
  /**
   * UUID
   * @type {string}
   * @memberof TwinCreationCertificate
   */
  readonly uuid?: string;
  /**
   * UTC timestamp denoting when Twin was created
   * @type {number}
   * @memberof TwinCreationCertificate
   */
  readonly createdTs?: number;
  /**
   * Account UUID of Account creating the Twin
   * @type {string}
   * @memberof TwinCreationCertificate
   */
  readonly creator?: string;
}

export function TwinCreationCertificateFromJSON(
  json: any
): TwinCreationCertificate {
  return TwinCreationCertificateFromJSONTyped(json, false);
}

export function TwinCreationCertificateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TwinCreationCertificate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: !exists(json, "uuid") ? undefined : json["uuid"],
    createdTs: !exists(json, "created_ts") ? undefined : json["created_ts"],
    creator: !exists(json, "creator") ? undefined : json["creator"],
  };
}

export function TwinCreationCertificateToJSON(
  value?: TwinCreationCertificate | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return value;
}
