/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.07.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  IndexColumns,
  IndexColumnsFromJSON,
  IndexColumnsFromJSONTyped,
  IndexColumnsToJSON,
} from "./IndexColumns";
import {
  IndexTableResponse,
  IndexTableResponseFromJSON,
  IndexTableResponseFromJSONTyped,
  IndexTableResponseToJSON,
} from "./IndexTableResponse";
import {
  IndexTableResponseStats,
  IndexTableResponseStatsFromJSON,
  IndexTableResponseStatsFromJSONTyped,
  IndexTableResponseStatsToJSON,
} from "./IndexTableResponseStats";
import {
  IndexTemplates,
  IndexTemplatesFromJSON,
  IndexTemplatesFromJSONTyped,
  IndexTemplatesToJSON,
} from "./IndexTemplates";

/**
 *
 * @export
 * @interface UpdateIndexesTable200Response
 */
export interface UpdateIndexesTable200Response {
  /**
   *
   * @type {IndexTableResponseStats}
   * @memberof UpdateIndexesTable200Response
   */
  stats: IndexTableResponseStats;
  /**
   * Rule
   * @type {string}
   * @memberof UpdateIndexesTable200Response
   */
  rule: string;
  /**
   *
   * @type {IndexColumns}
   * @memberof UpdateIndexesTable200Response
   */
  properties: IndexColumns;
  /**
   *
   * @type {IndexTemplates}
   * @memberof UpdateIndexesTable200Response
   */
  templates: IndexTemplates;
}

export function UpdateIndexesTable200ResponseFromJSON(
  json: any
): UpdateIndexesTable200Response {
  return UpdateIndexesTable200ResponseFromJSONTyped(json, false);
}

export function UpdateIndexesTable200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateIndexesTable200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    stats: IndexTableResponseStatsFromJSON(json["stats"]),
    rule: json["rule"],
    properties: IndexColumnsFromJSON(json["properties"]),
    templates: IndexTemplatesFromJSON(json["templates"]),
  };
}

export function UpdateIndexesTable200ResponseToJSON(
  value?: UpdateIndexesTable200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    stats: IndexTableResponseStatsToJSON(value.stats),
    rule: value.rule,
    properties: IndexColumnsToJSON(value.properties),
    templates: IndexTemplatesToJSON(value.templates),
  };
}
