/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserEntry
 */
export interface UserEntry {
    /**
     * User name
     * @type {string}
     * @memberof UserEntry
     */
    name?: string;
    /**
     * Role UUID
     * @type {string}
     * @memberof UserEntry
     */
    role?: string;
}

/**
 * Check if a given object implements the UserEntry interface.
 */
export function instanceOfUserEntry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserEntryFromJSON(json: any): UserEntry {
    return UserEntryFromJSONTyped(json, false);
}

export function UserEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function UserEntryToJSON(value?: UserEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'role': value.role,
    };
}

