/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.05.02
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRoleEntry
 */
export interface UserRoleEntry {
    /**
     * Role name
     * @type {string}
     * @memberof UserRoleEntry
     */
    name?: string;
    /**
     * UTC timestamp denoting when the Role was created
     * @type {string}
     * @memberof UserRoleEntry
     */
    createdTs?: string;
    /**
     * UTC timestamp denoting when the Role was last updated
     * @type {string}
     * @memberof UserRoleEntry
     */
    updatedTs?: string;
}

export function UserRoleEntryFromJSON(json: any): UserRoleEntry {
    return UserRoleEntryFromJSONTyped(json, false);
}

export function UserRoleEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdTs': !exists(json, 'created_ts') ? undefined : json['created_ts'],
        'updatedTs': !exists(json, 'updated_ts') ? undefined : json['updated_ts'],
    };
}

export function UserRoleEntryToJSON(value?: UserRoleEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'created_ts': value.createdTs,
        'updated_ts': value.updatedTs,
    };
}

