/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.02.00
 * Contact: api@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Ledger's value key
 * @export
 * @interface ValueEntry
 */
export interface ValueEntry {
    /**
     * value for corresponding Key
     * @type {string}
     * @memberof ValueEntry
     */
    value?: string;
    /**
     * type of value
     * @type {string}
     * @memberof ValueEntry
     */
    type?: ValueEntryTypeEnum;
    /**
     * Visibility of the Entry
     * @type {string}
     * @memberof ValueEntry
     */
    visibility?: string;
    /**
     * UTC timestamp denoting when the Entry was created
     * @type {number}
     * @memberof ValueEntry
     */
    readonly entryCreatedTs?: number;
    /**
     * UTC timestamp denoting when the Entry was last updated
     * @type {number}
     * @memberof ValueEntry
     */
    readonly entryUpdatedTs?: number;
    /**
     * UTC timestamp denoting when the Entry's value was last changed
     * @type {number}
     * @memberof ValueEntry
     */
    readonly valueChangedTs?: number;
}

/**
* @export
* @enum {string}
*/
export enum ValueEntryTypeEnum {
    String = 'string',
    Integer = 'integer',
    Datetime = 'datetime'
}

export function ValueEntryFromJSON(json: any): ValueEntry {
    return ValueEntryFromJSONTyped(json, false);
}

export function ValueEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValueEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'entryCreatedTs': !exists(json, 'entry_created_ts') ? undefined : json['entry_created_ts'],
        'entryUpdatedTs': !exists(json, 'entry_updated_ts') ? undefined : json['entry_updated_ts'],
        'valueChangedTs': !exists(json, 'value_changed_ts') ? undefined : json['value_changed_ts'],
    };
}

export function ValueEntryToJSON(value?: ValueEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'type': value.type,
        'visibility': value.visibility,
    };
}

