/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * This documentation describes API endpoints of the Trusted Twin platform.
 *
 * The version of the OpenAPI document: 2.05.02
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    WebhookSubscription,
    WebhookSubscriptionFromJSON,
    WebhookSubscriptionFromJSONTyped,
    WebhookSubscriptionToJSON,
} from './WebhookSubscription';

/**
 * 
 * @export
 * @interface WebhookSubscribeResponse
 */
export interface WebhookSubscribeResponse {
    /**
     * 
     * @type {WebhookSubscription}
     * @memberof WebhookSubscribeResponse
     */
    subscription?: WebhookSubscription;
    /**
     * URL to which notifications will be sent
     * @type {string}
     * @memberof WebhookSubscribeResponse
     */
    callbackUrl?: string;
    /**
     * Unix timestamp denoting till when subscription is valid
     * @type {number}
     * @memberof WebhookSubscribeResponse
     */
    validityTs?: number;
    /**
     * Returned only if client_secret provided, server-side generated part of key for hashing
     * @type {number}
     * @memberof WebhookSubscribeResponse
     */
    serverSecret?: number;
}

export function WebhookSubscribeResponseFromJSON(json: any): WebhookSubscribeResponse {
    return WebhookSubscribeResponseFromJSONTyped(json, false);
}

export function WebhookSubscribeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookSubscribeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subscription': !exists(json, 'subscription') ? undefined : WebhookSubscriptionFromJSON(json['subscription']),
        'callbackUrl': !exists(json, 'callback_url') ? undefined : json['callback_url'],
        'validityTs': !exists(json, 'validity_ts') ? undefined : json['validity_ts'],
        'serverSecret': !exists(json, 'server_secret') ? undefined : json['server_secret'],
    };
}

export function WebhookSubscribeResponseToJSON(value?: WebhookSubscribeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subscription': WebhookSubscriptionToJSON(value.subscription),
        'callback_url': value.callbackUrl,
        'validity_ts': value.validityTs,
        'server_secret': value.serverSecret,
    };
}

