/* tslint:disable */
/* eslint-disable */
/**
 * Trusted Twin API
 * TT API Gateway.
 *
 * The version of the OpenAPI document: 2.13.00
 * Contact: hello@trustedtwin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookUnsubscribeResponse
 */
export interface WebhookUnsubscribeResponse {
    /**
     * Topic name from which unsubscribe
     * @type {string}
     * @memberof WebhookUnsubscribeResponse
     */
    topic?: string;
    /**
     * Subscription uuid
     * @type {string}
     * @memberof WebhookUnsubscribeResponse
     */
    subscription?: string;
}

export function WebhookUnsubscribeResponseFromJSON(json: any): WebhookUnsubscribeResponse {
    return WebhookUnsubscribeResponseFromJSONTyped(json, false);
}

export function WebhookUnsubscribeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookUnsubscribeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topic': !exists(json, 'topic') ? undefined : json['topic'],
        'subscription': !exists(json, 'subscription') ? undefined : json['subscription'],
    };
}

export function WebhookUnsubscribeResponseToJSON(value?: WebhookUnsubscribeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topic': value.topic,
        'subscription': value.subscription,
    };
}

